"""
KCP Data Models

Defines the core data structures for knowledge artifacts.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional
from uuid import uuid4
import json


@dataclass
class Lineage:
    """Provenance information for a knowledge artifact."""
    query: str
    data_sources: list[str] = field(default_factory=list)
    agent: str = ""
    parent_reports: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "query": self.query,
            "data_sources": self.data_sources,
            "agent": self.agent,
            "parent_reports": self.parent_reports,
        }


@dataclass
class ACL:
    """Fine-grained access control for artifacts."""
    allowed_tenants: list[str] = field(default_factory=list)
    allowed_users: list[str] = field(default_factory=list)
    allowed_teams: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "allowed_tenants": self.allowed_tenants,
            "allowed_users": self.allowed_users,
            "allowed_teams": self.allowed_teams,
        }


@dataclass
class KnowledgeArtifact:
    """
    A KCP Knowledge Artifact.

    Represents any output generated by an AI agent — reports, analyses,
    visualizations, recommendations, etc.
    """
    # Required fields
    title: str
    user_id: str
    tenant_id: str
    format: str  # html, json, markdown, pdf, png, csv, text
    visibility: str = "private"  # public, org, team, private

    # Auto-generated
    id: str = field(default_factory=lambda: str(uuid4()))
    version: str = "1"
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    # Optional fields
    team: Optional[str] = None
    tags: list[str] = field(default_factory=list)
    source: str = ""
    summary: str = ""
    lineage: Optional[Lineage] = None
    content_url: str = ""
    content_hash: str = ""
    embeddings: list[float] = field(default_factory=list)
    signature: str = ""
    acl: Optional[ACL] = None

    def to_dict(self) -> dict:
        """Convert to KCP payload dict (for JSON serialization)."""
        d = {
            "id": self.id,
            "version": self.version,
            "user_id": self.user_id,
            "tenant_id": self.tenant_id,
            "timestamp": self.timestamp,
            "format": self.format,
            "visibility": self.visibility,
            "title": self.title,
            "content_hash": self.content_hash,
            "signature": self.signature,
        }
        # Optional fields (only include if set)
        if self.team:
            d["team"] = self.team
        if self.tags:
            d["tags"] = self.tags
        if self.source:
            d["source"] = self.source
        if self.summary:
            d["summary"] = self.summary
        if self.lineage:
            d["lineage"] = self.lineage.to_dict()
        if self.content_url:
            d["content_url"] = self.content_url
        if self.embeddings:
            d["embeddings"] = self.embeddings
        if self.acl:
            d["acl"] = self.acl.to_dict()
        return d

    def to_canonical_json(self) -> str:
        """
        Canonical JSON representation for signing.
        Sorted keys, compact separators, no signature field.
        """
        d = self.to_dict()
        d.pop("signature", None)
        return json.dumps(d, sort_keys=True, separators=(",", ":"))

    @classmethod
    def from_dict(cls, data: dict) -> "KnowledgeArtifact":
        """Create a KnowledgeArtifact from a dict (e.g., JSON response)."""
        lineage = None
        if "lineage" in data and data["lineage"]:
            lineage = Lineage(**data["lineage"])

        acl = None
        if "acl" in data and data["acl"]:
            acl = ACL(**data["acl"])

        return cls(
            id=data.get("id", str(uuid4())),
            version=data.get("version", "1"),
            user_id=data["user_id"],
            tenant_id=data["tenant_id"],
            timestamp=data.get("timestamp", datetime.now(timezone.utc).isoformat()),
            format=data["format"],
            visibility=data.get("visibility", "private"),
            title=data["title"],
            team=data.get("team"),
            tags=data.get("tags", []),
            source=data.get("source", ""),
            summary=data.get("summary", ""),
            lineage=lineage,
            content_url=data.get("content_url", ""),
            content_hash=data.get("content_hash", ""),
            embeddings=data.get("embeddings", []),
            signature=data.get("signature", ""),
            acl=acl,
        )


@dataclass
class SearchResult:
    """A single search result from DISCOVER operation."""
    id: str
    title: str
    summary: str
    created_at: str
    relevance: float
    format: str
    preview: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> "SearchResult":
        return cls(
            id=data["id"],
            title=data["title"],
            summary=data.get("summary", ""),
            created_at=data["created_at"],
            relevance=data.get("relevance", 0.0),
            format=data.get("format", ""),
            preview=data.get("preview", ""),
        )


@dataclass
class SearchResponse:
    """Response from DISCOVER operation."""
    results: list[SearchResult]
    total: int
    query_time_ms: int

    @classmethod
    def from_dict(cls, data: dict) -> "SearchResponse":
        return cls(
            results=[SearchResult.from_dict(r) for r in data.get("results", [])],
            total=data.get("total", 0),
            query_time_ms=data.get("query_time_ms", 0),
        )
