"""
KCP Data Models

Defines the core data structures for knowledge artifacts.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from uuid import uuid4


def normalize_expires_at(value) -> str | None:
    """
    Normalize a TTL deadline to a canonical UTC ISO 8601 string.

    Accepts ``None``, a ``datetime``, or a string (``Z`` suffix tolerated).
    Naive datetimes are assumed UTC. Normalizing matters because expiry is
    evaluated with a lexicographic comparison in SQLite: ``...Z`` sorts after
    ``...+00:00``, so mixed formats would break ``expires_at <= now``.
    """
    if value is None or value == "":
        return None
    if isinstance(value, datetime):
        dt = value
    else:
        raw = str(value).strip()
        if raw[-1:] in ("Z", "z"):
            raw = raw[:-1] + "+00:00"
        try:
            dt = datetime.fromisoformat(raw)
        except ValueError as exc:
            raise ValueError(f"Invalid expires_at — expected ISO 8601, got {value!r}") from exc
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc).isoformat()


def is_expired(expires_at, now: datetime | None = None) -> bool:
    """Return True when a normalized ``expires_at`` is in the past."""
    normalized = normalize_expires_at(expires_at)
    if not normalized:
        return False
    now = now or datetime.now(timezone.utc)
    if now.tzinfo is None:
        now = now.replace(tzinfo=timezone.utc)
    return normalized <= now.astimezone(timezone.utc).isoformat()


@dataclass
class Lineage:
    """Provenance information for a knowledge artifact."""

    query: str
    data_sources: list[str] = field(default_factory=list)
    agent: str = ""
    parent_reports: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "query": self.query,
            "data_sources": self.data_sources,
            "agent": self.agent,
            "parent_reports": self.parent_reports,
        }


@dataclass
class ACL:
    """Fine-grained access control for artifacts."""

    allowed_tenants: list[str] = field(default_factory=list)
    allowed_users: list[str] = field(default_factory=list)
    allowed_teams: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "allowed_tenants": self.allowed_tenants,
            "allowed_users": self.allowed_users,
            "allowed_teams": self.allowed_teams,
        }


# Lifecycle statuses for a knowledge artifact (KCP issue #4).
#   active      → current, discoverable knowledge
#   superseded  → a newer version of the same canonical artifact exists
#   expired     → its expires_at (TTL) is in the past
VALID_STATUSES = ("active", "superseded", "expired")

# Fields that are mutable lifecycle metadata — they change over the life of an
# artifact (supersede/expire) and are therefore NOT covered by the signature.
LIFECYCLE_FIELDS = ("status", "superseded_by")


@dataclass
class KnowledgeArtifact:
    """
    A KCP Knowledge Artifact.

    Represents any output generated by an AI agent — reports, analyses,
    visualizations, recommendations, etc.
    """

    # Required fields
    title: str
    user_id: str
    tenant_id: str
    format: str  # html, json, markdown, pdf, png, csv, text
    visibility: str = "private"  # public, org, team, private

    # Auto-generated
    id: str = field(default_factory=lambda: str(uuid4()))
    version: str = "1"
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    # Optional fields
    team: str | None = None
    tags: list[str] = field(default_factory=list)
    source: str = ""
    summary: str = ""
    lineage: Lineage | None = None
    content_url: str = ""
    content_hash: str = ""
    embeddings: list[float] = field(default_factory=list)
    signature: str = ""
    acl: ACL | None = None

    # Artifact versioning + lifecycle (KCP issue #4).
    # canonical_id is stable across all versions of the same knowledge item.
    canonical_id: str = ""
    expires_at: str | None = None
    status: str = "active"
    superseded_by: str = ""

    def to_dict(self, include_lifecycle: bool = False) -> dict:
        """
        Convert to KCP payload dict (for JSON serialization).

        Args:
            include_lifecycle: also include mutable lifecycle fields
                (``status``, ``superseded_by``). Defaults to False because this
                dict is the signed payload — lifecycle transitions (supersede /
                expiry) must not invalidate an artifact's signature.
        """
        d = {
            "id": self.id,
            "version": self.version,
            "user_id": self.user_id,
            "tenant_id": self.tenant_id,
            "timestamp": self.timestamp,
            "format": self.format,
            "visibility": self.visibility,
            "title": self.title,
            "content_hash": self.content_hash,
            "signature": self.signature,
        }
        # Immutable (signed) extension fields — only when set, so payloads
        # produced before the TTL/versioning extension keep verifying.
        if self.canonical_id:
            d["canonical_id"] = self.canonical_id
        if self.expires_at:
            d["expires_at"] = self.expires_at
        if include_lifecycle:
            d["status"] = self.status
            if self.superseded_by:
                d["superseded_by"] = self.superseded_by
        # Optional fields (only include if set)
        if self.team:
            d["team"] = self.team
        if self.tags:
            d["tags"] = self.tags
        if self.source:
            d["source"] = self.source
        if self.summary:
            d["summary"] = self.summary
        if self.lineage:
            d["lineage"] = self.lineage.to_dict()
        if self.content_url:
            d["content_url"] = self.content_url
        if self.embeddings:
            d["embeddings"] = self.embeddings
        if self.acl:
            d["acl"] = self.acl.to_dict()
        return d

    def to_canonical_json(self) -> str:
        """
        Canonical JSON representation for signing.
        Sorted keys, compact separators, no signature field.
        """
        d = self.to_dict()
        d.pop("signature", None)
        for key in LIFECYCLE_FIELDS:
            d.pop(key, None)
        return json.dumps(d, sort_keys=True, separators=(",", ":"))

    @classmethod
    def from_dict(cls, data: dict) -> KnowledgeArtifact:
        """Create a KnowledgeArtifact from a dict (e.g., JSON response)."""
        lineage = None
        if "lineage" in data and data["lineage"]:
            lineage = Lineage(**data["lineage"])

        acl = None
        if "acl" in data and data["acl"]:
            acl = ACL(**data["acl"])

        return cls(
            id=data.get("id", str(uuid4())),
            version=data.get("version", "1"),
            user_id=data["user_id"],
            tenant_id=data["tenant_id"],
            timestamp=data.get("timestamp", datetime.now(timezone.utc).isoformat()),
            format=data["format"],
            visibility=data.get("visibility", "private"),
            title=data["title"],
            team=data.get("team"),
            tags=data.get("tags", []),
            source=data.get("source", ""),
            summary=data.get("summary", ""),
            lineage=lineage,
            content_url=data.get("content_url", ""),
            content_hash=data.get("content_hash", ""),
            embeddings=data.get("embeddings", []),
            signature=data.get("signature", ""),
            acl=acl,
            canonical_id=data.get("canonical_id", "") or "",
            expires_at=data.get("expires_at") or None,
            status=data.get("status", "active") or "active",
            superseded_by=data.get("superseded_by", "") or "",
        )


@dataclass
class SearchResult:
    """A single search result from DISCOVER operation.

    ``relevance`` is the ranking score reported to clients (BM25-derived for
    keyword search, cosine for semantic search, fused score for hybrid search).
    ``scores`` optionally exposes the raw components, e.g.
    ``{"keyword": 0.8, "semantic": 0.4, "fused": 0.6}`` for hybrid search.
    """

    id: str
    title: str
    summary: str
    created_at: str
    relevance: float
    format: str
    preview: str = ""
    status: str = "active"
    canonical_id: str = ""
    scores: dict = field(default_factory=dict)

    @classmethod
    def from_dict(cls, data: dict) -> SearchResult:
        return cls(
            id=data["id"],
            title=data["title"],
            summary=data.get("summary", ""),
            created_at=data["created_at"],
            relevance=data.get("relevance", 0.0),
            format=data.get("format", ""),
            preview=data.get("preview", ""),
            status=data.get("status", "active"),
            canonical_id=data.get("canonical_id", ""),
            scores=data.get("scores", {}),
        )


@dataclass
class SearchResponse:
    """Response from DISCOVER operation."""

    results: list[SearchResult]
    total: int
    query_time_ms: int

    @classmethod
    def from_dict(cls, data: dict) -> SearchResponse:
        return cls(
            results=[SearchResult.from_dict(r) for r in data.get("results", [])],
            total=data.get("total", 0),
            query_time_ms=data.get("query_time_ms", 0),
        )
